version: "3.8"

services:
  app:
    container_name: shoppingbackend
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mysql
    volumes:
      - .:/app

  mysql:
    container_name: mysqldatabase
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: shoppinglist
      MYSQL_USER: kevin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
